# Generated by Django 4.2.3 on 2023-11-14 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_book_bookmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='published_date',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='book_name',
            field=models.CharField(default='booksa', max_length=100),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='category',
            field=models.CharField(choices=[('category', 'category'), ('Hurrur', 'hurrur'), ('mistry', 'mistry'), ('humar', 'humar'), ('ci fi', 'ci fi')], default='hurrur', max_length=30),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='description',
            field=models.TextField(default='books'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='first_pub',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='last_pub',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
