# Generated by Django 4.2.3 on 2023-11-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_bookmodel_published_date_bookmodel_book_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='last_pub',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='bookmodel',
            old_name='first_pub',
            new_name='published_date',
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='category',
            field=models.CharField(default='hurrur', max_length=30),
        ),
    ]
